export function RiskAssessmentCard() {
  return (
    <div className="bg-white dark:bg-[#1a190b] rounded-xl p-0 shadow-sm border border-neutral-100 dark:border-neutral-700 overflow-hidden flex flex-col h-full">
      <div className="bg-primary/10 p-6 border-b border-primary/20">
        <div className="flex items-start gap-4">
          <div className="bg-primary text-neutral-dark rounded-full p-2 shrink-0">
            <span className="material-symbols-outlined">analytics</span>
          </div>
          <div>
            <h3 className="text-lg font-bold text-neutral-dark dark:text-white leading-tight">High Risk of Stock-out</h3>
            <p className="text-sm font-medium text-neutral-500 mt-1">Predicted in <span className="text-neutral-dark dark:text-white font-bold underline decoration-primary decoration-2">4 Days</span></p>
          </div>
        </div>
      </div>
      <div className="p-6 flex flex-col gap-6 flex-1">
        {/* AI Explanation */}
        <div>
          <p className="text-xs uppercase tracking-wider font-bold text-neutral-500 mb-3">Why this prediction?</p>
          <ul className="flex flex-col gap-3">
            <li className="flex gap-3 text-sm leading-relaxed">
              <span className="material-symbols-outlined text-primary text-[20px] shrink-0">trending_up</span>
              <span>
                <strong className="block text-neutral-dark dark:text-white">Usage Spike (+20%)</strong>
                <span className="text-neutral-500">Consumption increased sharply yesterday, deviating from normal trends.</span>
              </span>
            </li>
            <li className="flex gap-3 text-sm leading-relaxed">
              <span className="material-symbols-outlined text-primary text-[20px] shrink-0">flood</span>
              <span>
                <strong className="block text-neutral-dark dark:text-white">Regional Event</strong>
                <span className="text-neutral-500">Correlated with recent flood reports in the district, increasing antibiotic demand.</span>
              </span>
            </li>
          </ul>
        </div>
        <hr className="border-neutral-100 dark:border-neutral-700" />
        {/* Recommended Action */}
        <div>
          <p className="text-xs uppercase tracking-wider font-bold text-neutral-500 mb-3">Recommended Action</p>
          <div className="bg-background-light dark:bg-[#23220f] p-4 rounded-xl border border-neutral-100 dark:border-neutral-700">
            <p className="text-sm font-medium mb-3 text-neutral-dark dark:text-white">Transfer stock from nearby healthy inventory.</p>
            <button className="w-full py-2 px-4 bg-white dark:bg-[#1a190b] border border-neutral-200 dark:border-neutral-600 rounded-lg text-sm font-bold shadow-sm hover:border-primary transition-colors flex items-center justify-center gap-2 text-neutral-dark dark:text-white">
              <span>Request 50 Units</span>
              <span className="material-symbols-outlined text-[16px]">arrow_forward</span>
            </button>
            <p className="text-[10px] text-center text-neutral-500 mt-2">Source: District Hospital (15km away)</p>
          </div>
        </div>
      </div>
      <div className="bg-primary/5 p-3 text-center border-t border-neutral-100 dark:border-neutral-700">
        <p className="text-[10px] text-neutral-500 flex items-center justify-center gap-1">
          <span className="material-symbols-outlined text-[12px]">psychology</span>
          Generated by StockHealth AI • 89% Confidence
        </p>
      </div>
    </div>
  );
}
