-- Snowflake Schema Creation Script for LedgerShield
-- Run this in Snowflake Web UI Worksheets

USE DATABASE INVENTORYDB;
USE SCHEMA SUPPLY_CHAIN;

-- Create STORES table
CREATE TABLE IF NOT EXISTS STORES (
    ID VARCHAR(255) PRIMARY KEY,
    NAME VARCHAR(255) NOT NULL,
    SECTION VARCHAR(50) NOT NULL,
    CONTAINER_NAME VARCHAR(255),
    STATUS VARCHAR(50) DEFAULT 'ACTIVE',
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- Create ITEMS table
CREATE TABLE IF NOT EXISTS ITEMS (
    ID VARCHAR(255) PRIMARY KEY,
    NAME VARCHAR(255) NOT NULL,
    CATEGORY VARCHAR(100),
    QUANTITY NUMBER(10,2) DEFAULT 0,
    PRICE NUMBER(10,2) DEFAULT 0,
    STATUS VARCHAR(50),
    LAST_UPDATED TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    EXPIRY_DATE TIMESTAMP_NTZ,
    MANUFACTURING_DATE TIMESTAMP_NTZ,
    BATCH_NUMBER VARCHAR(100),
    SUPPLIER VARCHAR(255),
    DESCRIPTION TEXT,
    UNIT VARCHAR(50),
    MIN_QUANTITY NUMBER(10,2),
    OWNER_ID VARCHAR(255),
    SECTION VARCHAR(50) NOT NULL
);

-- Create TRANSACTIONS table
CREATE TABLE IF NOT EXISTS TRANSACTIONS (
    ID VARCHAR(255) PRIMARY KEY,
    INVOICE_NUMBER VARCHAR(100) NOT NULL,
    DATE TIMESTAMP_NTZ NOT NULL,
    TYPE VARCHAR(50) NOT NULL, -- SALE, INTERNAL_USAGE, DAMAGE, EXPIRY
    ITEMS VARIANT, -- JSON array
    TOTAL_AMOUNT NUMBER(10,2),
    PAYMENT_METHOD VARCHAR(50),
    CUSTOMER_NAME VARCHAR(255),
    CUSTOMER_CONTACT VARCHAR(100),
    SECTION VARCHAR(50) NOT NULL,
    PERFORMED_BY VARCHAR(255)
);

-- Create ACTIVITIES table  
CREATE TABLE IF NOT EXISTS ACTIVITIES (
    ID VARCHAR(255) PRIMARY KEY,
    USER_ID VARCHAR(255) NOT NULL,
    ACTION VARCHAR(255) NOT NULL,
    TARGET VARCHAR(255),
    TIME TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    TYPE VARCHAR(50), -- update, create, delete, alert
    SECTION VARCHAR(50) NOT NULL
);

-- Create PURCHASE_ORDERS table
CREATE TABLE IF NOT EXISTS PURCHASE_ORDERS (
    ID VARCHAR(255) PRIMARY KEY,
    PO_NUMBER VARCHAR(100) NOT NULL,
    DATE_CREATED TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    STATUS VARCHAR(50) NOT NULL, -- DRAFT, PENDING, APPROVED, PARTIALLY_RECEIVED, RECEIVED, CANCELLED
    ITEMS VARIANT, -- JSON array
    TOTAL_ESTIMATED_COST NUMBER(10,2),
    VENDOR VARCHAR(255),
    NOTES TEXT,
    CREATED_BY VARCHAR(255),
    APPROVED_BY VARCHAR(255),
    RECEIVED_DATE TIMESTAMP_NTZ
);

-- Verify tables were created
SHOW TABLES;
